name: quill_native_bridge_web
description: "Web platform implementation of quill_native_bridge"
version: 0.0.1-dev.6
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_web
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_web
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues?q=is%3Aissue+is%3Aopen+label%3A%22platform-web%22
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_web
topics: [ clipboard, os-integration, quill-native-bridge, quill, flutter-quill ]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  quill_native_bridge_platform_interface:
    path: ../quill_native_bridge_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: quill_native_bridge
    platforms:
      web:
        pluginClass: QuillNativeBridgeWeb
        fileName: quill_native_bridge_web.dart
