name: quill_native_bridge_linux
description: "Linux implementation of the quill_native_bridge plugin."
version: 0.0.1-dev.4
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_linux
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_linux
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues?q=is%3Aissue+is%3Aopen+label%3A%22platform-linux%22
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_linux
topics: [ clipboard, os-integration, quill-native-bridge, quill, flutter-quill ]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  quill_native_bridge_platform_interface:
    path: ../quill_native_bridge_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  crypto: ^3.0.5
  yaml: ^3.1.2

flutter:
  plugin:
    implements: quill_native_bridge
    platforms:
      linux:
        pluginClass: none
        dartPluginClass: QuillNativeBridgeLinux
        fileName: quill_native_bridge_linux.dart