name: quill_native_bridge
description: "An internal plugin for flutter_quill package to access platform-specific APIs"
version: 10.7.11
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge
topics: [ clipboard, os-integration, quill-native-bridge, quill, flutter-quill ]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  quill_native_bridge_android:
    path: ../quill_native_bridge_android
  quill_native_bridge_platform_interface:
    path: ../quill_native_bridge_platform_interface
  quill_native_bridge_web:
    path: ../quill_native_bridge_web
  quill_native_bridge_windows:
    path: ../quill_native_bridge_windows
  quill_native_bridge_linux:
    path: ../quill_native_bridge_linux
  quill_native_bridge_ios:
    path: ../quill_native_bridge_ios
  quill_native_bridge_macos:
    path: ../quill_native_bridge_macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: quill_native_bridge_android
      ios:
        default_package: quill_native_bridge_ios
      macos:
        default_package: quill_native_bridge_macos
      web:
        default_package: quill_native_bridge_web
      windows:
        default_package: quill_native_bridge_windows
      linux:
        default_package: quill_native_bridge_linux