name: quill_native_bridge_windows
description: "Windows implementation of the quill_native_bridge plugin."
version: 0.0.1-dev.4
homepage: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_windows
repository: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_windows
issue_tracker: https://github.com/FlutterQuill/quill-native-bridge/issues?q=is%3Aissue+is%3Aopen+label%3A%22platform-windows%22
documentation: https://github.com/FlutterQuill/quill-native-bridge/tree/main/quill_native_bridge_windows
topics: [ clipboard, os-integration, quill-native-bridge, quill, flutter-quill ]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  quill_native_bridge_platform_interface:
    path: ../quill_native_bridge_platform_interface
  win32: ^5.5.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: quill_native_bridge
    platforms:
      windows:
        pluginClass: none
        dartPluginClass: QuillNativeBridgeWindows
        fileName: quill_native_bridge_windows.dart
